name: zest_desktop
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #国际化
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  signals: ^6.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  get_it: ^8.0.3
  flutter_hooks: ^0.21.2

  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0 #dio请求日志
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  logger: ^2.5.0 #log日志
  ansi_styles: ^0.3.2+1 #控制台输出颜色
  flutter_dotenv: ^5.2.1 #管理多个环境
  device_preview: ^1.2.0 #设备预览

  flutter_staggered_grid_view: ^0.7.0 #瀑布流
  flutter_easyloading: ^3.0.5 #加载动画
  flutter_screenutil: ^5.9.3 #屏幕适配
  easy_refresh: ^3.4.0 #下拉刷新

  get_storage: ^2.1.1
  shared_preferences: ^2.3.5
  event_bus: ^2.0.1 #事件总线
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.1
  package_info_plus: ^8.1.3
  android_id: ^0.4.0
  encrypt: ^5.0.3 #加密
  flutter_form_builder: ^9.5.0 #表单
  intl: ^0.19.0 #国际化
  adaptive_theme: ^3.6.0 #设置明暗主题
  secure_application: ^4.1.0 #应用切换到后台隐藏内容
  flutter_cache_manager: ^3.4.1 #缓存
  awesome_extensions: ^2.0.21 #扩展集合

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.14.3 #启动图生成
  flutter_native_splash: ^2.4.4 #闪屏页生成
#  dart run change_app_package_name:main com.new.package.name
#  dart run change_app_package_name:main com.new.package.name --android
#  dart run change_app_package_name:main com.new.package.name --ios
  change_app_package_name: ^1.5.0 #修改包名
  envied_generator: ^1.1.1 #环境变量


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: IconUntil
      fonts:
        - asset: assets/icon_font/icon_until.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/
    - assets/images/
    - assets/locales/
    - assets/models/
    - lib/core/env/

# intl_utils插件 cli工具 配置:
#命令：dart run intl_utils:generate
flutter_intl:
  enabled: false #是否激活
  class_name: S #设置生成的本地化类的名称。默认值：S
  main_locale: en #设置用于生成本地化文件的主要语言环境, 默认值：en
  arb_dir: lib/generated/l10n #设置 ARB 资源文件的目录,默认值：lib/l10n
  output_dir: lib/generated #设置生成的本地化文件的目录,默认值：lib/generated

# Flutter Assets Gen插件(vscode) 配置
flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  ignore_comments: true
  field_prefix:
  class_name: Assets


##  本地的get_cli工具：字体图标配置 命令 get_cli generate icons
#flutter_icons:
#  src_zip: 'assets/download.zip' # 下载的字体图标压缩包资源路径
#  assets_dir: 'assets/icon_font/'  # ttf文件解压的文件夹
#  dist_file: 'lib/app/data/utils/icon_until.dart' # 生成的代码文件路径



#命令：dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo.png"

# dart run flutter_native_splash:create
# dart run flutter_native_splash:remove
flutter_native_splash:
  background_image: "assets/images/app_launcher_splash_2.png"
  android: true
  ios: true
  web: false

  android_gravity: fill
  ios_content_mode: scaleToFill
  web_image_mode: center

  android_12:
    image: "assets/images/app_logo.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/app_logo.png"
    icon_background_color_dark: "#121212"
